twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        getServiceDescription: '@App\Twig\FunctionExtension'

when@test:
    twig:
        strict_variables: true
