controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: fr|en
    defaults:
        _locale: '%locale%'
app_home:
    path: /{_locale}
    controller: App\Controller\HomeController::index
    defaults:
        template: pages/home/index.html.twig
        _locale: '%locale%'
